#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadEnv } from './load-env.mjs';

loadEnv();

const __dirname = dirname(fileURLToPath(import.meta.url));
const publicDir = join(__dirname, '..', 'public');
const coreDir = join(publicDir, 'assets', 'js', 'core');

function normalizeSiteUrl(url) {
  let u = (url || 'http://localhost:3000').trim().replace(/\/$/, '');
  if (!/^https?:\/\//i.test(u)) u = `https://${u}`;
  return u;
}

const siteUrl = normalizeSiteUrl(process.env.SITE_URL);
// Local default: backend on :4000. On Vercel, always set API_URL.
const apiUrl = (process.env.API_URL || 'http://localhost:4000').replace(/\/$/, '');
const neonAuthUrl = process.env.NEON_AUTH_URL || '';
const googleVerification = process.env.GOOGLE_SITE_VERIFICATION || 'GWlm1cpN7bEXema60NG3J64EbbJ5VbOZnon6exzgZ1s';
const ogImage = process.env.OG_IMAGE_URL || '/assets/img/og-cover.jpg';

const ogImagePath = ogImage.startsWith('http')
  ? ogImage
  : `${siteUrl}${ogImage.startsWith('/') ? '' : '/'}${ogImage}`;

const config = `// Auto-generated by scripts/inject-config.mjs — do not edit
export const API_BASE = ${JSON.stringify(apiUrl)};
export const NEON_AUTH_URL = ${JSON.stringify(neonAuthUrl)};
export const SITE_URL = ${JSON.stringify(siteUrl)};
`;
await writeFile(join(coreDir, 'config.js'), config, 'utf8');

const indexPath = join(publicDir, 'index.html');
let html = await readFile(indexPath, 'utf8');

const runtimeSnippet = `<script>window.__FENLO_API_URL__=${JSON.stringify(apiUrl)};window.__FENLO_NEON_AUTH_URL__=${JSON.stringify(neonAuthUrl)};window.__FENLO_SITE_URL__=${JSON.stringify(siteUrl)};</script>`;

if (html.includes('<!-- fenlo-config -->')) {
  html = html.replace(/<!-- fenlo-config -->[\s\S]*?<!-- \/fenlo-config -->/, `<!-- fenlo-config -->\n${runtimeSnippet}\n<!-- /fenlo-config -->`);
}

const googleMeta = googleVerification
  ? `<meta name="google-site-verification" content="${googleVerification}">`
  : '<!-- google-site-verification: set GOOGLE_SITE_VERIFICATION in Vercel -->';

const seoBlock = `<!-- fenlo-seo -->
<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">
<meta name="author" content="Fenlo">
<link rel="canonical" href="${siteUrl}/">
<meta property="og:type" content="website">
<meta property="og:site_name" content="Fenlo">
<meta property="og:title" content="Fenlo · AI Assignment Completion Platform">
<meta property="og:description" content="Upload your assignment — get a polished answer back. Full assignment or direct solution. Export to PDF, Word, TXT, or Markdown.">
<meta property="og:url" content="${siteUrl}/">
<meta property="og:image" content="${ogImagePath}">
<meta property="og:image:secure_url" content="${ogImagePath}">
<meta property="og:image:type" content="${ogImagePath.endsWith('.png') ? 'image/png' : ogImagePath.endsWith('.svg') ? 'image/svg+xml' : 'image/jpeg'}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Fenlo — Upload your assignment, get a polished answer back">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="Fenlo · AI Assignment Completion Platform">
<meta name="twitter:description" content="Upload your assignment — get a polished answer back. Export to PDF, Word, TXT, or Markdown.">
<meta name="twitter:image" content="${ogImagePath}">
<link rel="image_src" href="${ogImagePath}">
${googleMeta}
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "${siteUrl}/#org",
      "name": "Fenlo",
      "url": "${siteUrl}/",
      "logo": "${siteUrl}/assets/img/fenlo-logo.svg",
      "description": "AI assignment completion platform for students."
    },
    {
      "@type": "WebSite",
      "@id": "${siteUrl}/#site",
      "url": "${siteUrl}/",
      "name": "Fenlo",
      "description": "Upload your assignment — get a polished answer back.",
      "publisher": { "@id": "${siteUrl}/#org" },
      "inLanguage": "en"
    },
    {
      "@type": "WebApplication",
      "@id": "${siteUrl}/#app",
      "name": "Fenlo",
      "url": "${siteUrl}/",
      "applicationCategory": "EducationalApplication",
      "operatingSystem": "Web",
      "description": "AI-powered assignment helper. Upload text or files, choose full assignment or direct answer, export to PDF, DOCX, TXT, or Markdown.",
      "offers": {
        "@type": "Offer",
        "price": "0",
        "priceCurrency": "USD"
      }
    }
  ]
}
</script>
<!-- /fenlo-seo -->`;

if (html.includes('<!-- fenlo-seo -->')) {
  html = html.replace(/<!-- fenlo-seo -->[\s\S]*?<!-- \/fenlo-seo -->/, seoBlock);
} else {
  html = html.replace('</head>', `${seoBlock}\n</head>`);
}

await writeFile(indexPath, html, 'utf8');

console.log('built config.js — API_BASE:', apiUrl || '(same origin)');
console.log('built config.js — SITE_URL:', siteUrl);
console.log('injected SEO + runtime into index.html');
console.log('OG image:', ogImagePath);
