#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..', 'public', 'assets', 'js', 'core');

const apiUrl = (process.env.API_URL || '').replace(/\/$/, '');
const neonAuthUrl = process.env.NEON_AUTH_URL || '';

const config = `// Auto-generated by scripts/inject-config.mjs — do not edit
export const API_BASE = ${JSON.stringify(apiUrl)};
export const NEON_AUTH_URL = ${JSON.stringify(neonAuthUrl)};
`;

await writeFile(join(root, 'config.js'), config, 'utf8');
console.log('built config.js — API_BASE:', apiUrl || '(same origin)');

// Inject runtime globals into index.html placeholder
const indexPath = join(__dirname, '..', 'public', 'index.html');
let html = await readFile(indexPath, 'utf8');
const snippet = `<script>window.__FENLO_API_URL__=${JSON.stringify(apiUrl)};window.__FENLO_NEON_AUTH_URL__=${JSON.stringify(neonAuthUrl)};</script>`;

if (html.includes('<!-- fenlo-config -->')) {
  html = html.replace(/<!-- fenlo-config -->[\s\S]*?<!-- \/fenlo-config -->/, `<!-- fenlo-config -->\n${snippet}\n<!-- /fenlo-config -->`);
} else {
  html = html.replace('</head>', `${snippet}\n</head>`);
}

await writeFile(indexPath, html, 'utf8');
console.log('injected config into index.html');
